"""Add reading orders tables

Revision ID: 041f865a9717
Revises: b9ec6f922a61
Create Date: 2026-06-25 20:42:54.962419

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '041f865a9717'
down_revision: str | Sequence[str] | None = 'b9ec6f922a61'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reading_order_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('issue_number', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['reading_order_id'], ['reading_orders.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.create_index('uq_collections_user_default', ['user_id'], unique=True, postgresql_where=sa.text('is_default = TRUE'))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('events_session_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('events_thread_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'threads', ['thread_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_review_user_thread_issue'), postgresql_nulls_not_distinct=True)
        batch_op.create_index('uq_review_user_thread_issue', ['user_id', 'thread_id', 'issue_id'], unique=True)
        batch_op.drop_constraint(batch_op.f('reviews_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('sessions_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('snapshots_event_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('snapshots_session_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'events', ['event_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'sessions', ['session_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('snapshots_session_id_fkey'), 'sessions', ['session_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('snapshots_event_id_fkey'), 'events', ['event_id'], ['id'])

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('sessions_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('reviews_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.drop_index('uq_review_user_thread_issue')
        batch_op.create_index(batch_op.f('uq_review_user_thread_issue'), ['user_id', 'thread_id', 'issue_id'], unique=True, postgresql_nulls_not_distinct=True)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('events_thread_id_fkey'), 'threads', ['thread_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('events_session_id_fkey'), 'sessions', ['session_id'], ['id'])

    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_index('uq_collections_user_default', postgresql_where=sa.text('is_default = TRUE'))

    op.drop_table('reading_order_items')
    op.drop_table('reading_orders')
    # ### end Alembic commands ###
