"""Add composite indexes for Thread and Session queries

Revision ID: 0e45016da0d7
Revises: 1ede41fd37e4
Create Date: 2026-02-03 19:34:05.663119

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e45016da0d7'
down_revision: str | Sequence[str] | None = '1ede41fd37e4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('events_thread_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'threads', ['thread_id'], ['id'])

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('ix_session_user_ended_started', ['user_id', 'ended_at', 'started_at'], unique=False)

    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('snapshots_event_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'events', ['event_id'], ['id'])

    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.create_index('ix_thread_user_status_position', ['user_id', 'status', 'queue_position'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.drop_index('ix_thread_user_status_position')

    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('snapshots_event_id_fkey'), 'events', ['event_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_session_user_ended_started')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('events_thread_id_fkey'), 'threads', ['thread_id'], ['id'], ondelete='CASCADE')

    op.create_table('settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_gap_hours', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_die', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating_min', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('rating_max', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('rating_step', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('rating_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('settings_pkey'))
    )
    # ### end Alembic commands ###
