"""add skipped_thread_ids to sessions

Revision ID: 37a821bf4182
Revises: d3b4e6f8a0c2
Create Date: 2026-08-31 11:41:24.838652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37a821bf4182'
down_revision: Union[str, Sequence[str], None] = 'd3b4e6f8a0c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('migration_data_deletion_audit')
    with op.batch_alter_table('continuity_plans', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ck_continuity_plans_ordering_mode'), type_='check')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('context',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Optional decision-context metadata captured at event time',
               existing_nullable=True)
        batch_op.alter_column('rolling_recommendation_context',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Versioned snapshot of recommendation context captured at roll decision time',
               existing_nullable=True)

    with op.batch_alter_table('external_identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_identity_metadata_jsonb_path'), postgresql_ops={'(metadata_json::jsonb)': 'jsonb_path_ops'}, postgresql_using='gin')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skipped_thread_ids', sa.JSON(), nullable=True))
        batch_op.alter_column('predicted_bandwidth',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Predicted bandwidth at session start: light, balanced, or deep',
               existing_nullable=True)
        batch_op.alter_column('active_bandwidth',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Current active bandwidth: light, balanced, or deep',
               existing_nullable=True)
        batch_op.alter_column('bandwidth_confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Confidence in the active bandwidth (0.0-1.0)',
               existing_nullable=True)
        batch_op.alter_column('bandwidth_source',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='Source of the bandwidth state: inferred, manual, snooze, or quiz',
               existing_nullable=True)
        batch_op.alter_column('bandwidth_version',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Mode/algorithm version that produced the bandwidth state',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('bandwidth_version',
               existing_type=sa.VARCHAR(length=50),
               comment='Mode/algorithm version that produced the bandwidth state',
               existing_nullable=True)
        batch_op.alter_column('bandwidth_source',
               existing_type=sa.VARCHAR(length=30),
               comment='Source of the bandwidth state: inferred, manual, snooze, or quiz',
               existing_nullable=True)
        batch_op.alter_column('bandwidth_confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Confidence in the active bandwidth (0.0-1.0)',
               existing_nullable=True)
        batch_op.alter_column('active_bandwidth',
               existing_type=sa.VARCHAR(length=20),
               comment='Current active bandwidth: light, balanced, or deep',
               existing_nullable=True)
        batch_op.alter_column('predicted_bandwidth',
               existing_type=sa.VARCHAR(length=20),
               comment='Predicted bandwidth at session start: light, balanced, or deep',
               existing_nullable=True)
        batch_op.drop_column('skipped_thread_ids')

    with op.batch_alter_table('external_identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_identity_metadata_jsonb_path'), [sa.literal_column('(metadata_json::jsonb)')], unique=False, postgresql_ops={'(metadata_json::jsonb)': 'jsonb_path_ops'}, postgresql_using='gin')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('rolling_recommendation_context',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Versioned snapshot of recommendation context captured at roll decision time',
               existing_nullable=True)
        batch_op.alter_column('context',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Optional decision-context metadata captured at event time',
               existing_nullable=True)

    with op.batch_alter_table('continuity_plans', schema=None) as batch_op:
        batch_op.create_check_constraint(batch_op.f('ck_continuity_plans_ordering_mode'), "ordering_mode::text = ANY (ARRAY['informational'::character varying, 'strict_sequential'::character varying]::text[])")

    op.create_table('migration_data_deletion_audit',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('migration_revision', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('resource', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('row_count', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('migration_data_deletion_audit_pkey'))
    )
    # ### end Alembic commands ###
