"""Add composite indexes to Event table for performance optimization

Revision ID: 408b0e691539
Revises: b1a2c3d4e5f6
Create Date: 2026-01-10 14:06:31.356996

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '408b0e691539'
down_revision: str | Sequence[str] | None = 'b1a2c3d4e5f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_event_session_type_die_after', ['session_id', 'type', 'die_after'], unique=False)
        batch_op.create_index('ix_event_session_type_timestamp', ['session_id', 'type', 'timestamp'], unique=False)

    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.alter_column('is_test',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.alter_column('is_test',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_event_session_type_timestamp')
        batch_op.drop_index('ix_event_session_type_die_after')

    # ### end Alembic commands ###
