"""add issue tracking

Revision ID: 9f97c046466f
Revises: bd20a5b1d883
Create Date: 2026-02-24 19:11:08.502431

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9f97c046466f"
down_revision: str | Sequence[str] | None = "bd20a5b1d883"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "issues",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("thread_id", sa.Integer(), nullable=False),
        sa.Column("issue_number", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["thread_id"], ["threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("issues", schema=None) as batch_op:
        batch_op.create_index("ix_issue_thread_id", ["thread_id"], unique=False)
        batch_op.create_index("ix_issue_thread_is_read", ["thread_id", "status"], unique=False)
        batch_op.create_index("ix_issue_thread_number", ["thread_id", "issue_number"], unique=False)

    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("issue_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("issue_number", sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(
            "fk_events_issue_id", "issues", ["issue_id"], ["id"], ondelete="SET NULL"
        )

    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("pending_issue_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_sessions_pending_issue_id",
            "issues",
            ["pending_issue_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("threads", schema=None) as batch_op:
        batch_op.add_column(sa.Column("total_issues", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("next_unread_issue_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("reading_progress", sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column("blocked_by_thread_ids", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("blocked_by_issue_ids", sa.JSON(), nullable=True))
        batch_op.create_index("ix_thread_collection_id", ["collection_id"], unique=False)
        batch_op.create_foreign_key(
            "fk_threads_next_unread_issue_id",
            "issues",
            ["next_unread_issue_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("threads", schema=None) as batch_op:
        batch_op.drop_constraint("fk_threads_next_unread_issue_id", type_="foreignkey")
        batch_op.drop_index("ix_thread_collection_id")
        batch_op.drop_column("blocked_by_issue_ids")
        batch_op.drop_column("blocked_by_thread_ids")
        batch_op.drop_column("reading_progress")
        batch_op.drop_column("next_unread_issue_id")
        batch_op.drop_column("total_issues")

    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_constraint("fk_sessions_pending_issue_id", type_="foreignkey")
        batch_op.drop_column("pending_issue_id")

    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_constraint("fk_events_issue_id", type_="foreignkey")
        batch_op.drop_column("issue_number")
        batch_op.drop_column("issue_id")

    with op.batch_alter_table("issues", schema=None) as batch_op:
        batch_op.drop_index("ix_issue_thread_number")
        batch_op.drop_index("ix_issue_thread_is_read")
        batch_op.drop_index("ix_issue_thread_id")

    op.drop_table("issues")
    # ### end Alembic commands ###
