"""add collections

Revision ID: bd20a5b1d883
Revises: 58c2d0ee93f3
Create Date: 2026-02-23 08:14:40.862924

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bd20a5b1d883"
down_revision: str | Sequence[str] | None = "58c2d0ee93f3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("threads", schema=None) as batch_op:
        batch_op.add_column(sa.Column("collection_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_threads_collection_id_collections",
            "collections",
            ["collection_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_index("ix_threads_collection_id", ["collection_id"])

    # ### end Alembic commands ###

    # Create default collection for existing users
    op.execute("""
        INSERT INTO collections (name, user_id, is_default, position, created_at)
        SELECT 'My Comics', id, true, 0, created_at
        FROM users
        WHERE NOT EXISTS (
            SELECT 1 FROM collections WHERE collections.user_id = users.id
        )
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("threads", schema=None) as batch_op:
        batch_op.drop_index("ix_threads_collection_id")
        batch_op.drop_constraint("fk_threads_collection_id_collections", type_="foreignkey")
        batch_op.drop_column("collection_id")

    op.drop_table("collections")
    # ### end Alembic commands ###
