"""Add reviews table

Revision ID: be75ffc829e2
Revises: a4e6b7c8d9f0
Create Date: 2026-04-04 18:41:56.362532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be75ffc829e2'
down_revision: Union[str, Sequence[str], None] = 'a4e6b7c8d9f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dependencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(length=255), nullable=True))

    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.drop_column('blocked_by_issue_ids')
        batch_op.drop_column('blocked_by_thread_ids')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blocked_by_thread_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('blocked_by_issue_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))

    with op.batch_alter_table('dependencies', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
