"""Add reviews table

Revision ID: be75ffc829e2
Revises: a4e6b7c8d9f0
Create Date: 2026-04-04 18:41:56.362532

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "be75ffc829e2"
down_revision: str | Sequence[str] | None = "a4e6b7c8d9f0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create reviews table
    op.create_table(
        "reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("thread_id", sa.Integer(), nullable=False),
        sa.Column("issue_id", sa.Integer(), nullable=True),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("review_text", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["issue_id"], ["issues.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["threads.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "thread_id", "issue_id", name="uq_review_user_thread_issue"),
    )

    # Create indexes for reviews table
    op.create_index("ix_review_user_thread", "reviews", ["user_id", "thread_id"])
    op.create_index("ix_review_created_at", "reviews", ["created_at"])
    op.create_index("ix_review_thread_id", "reviews", ["thread_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop reviews table and its indexes
    op.drop_index("ix_review_thread_id", table_name="reviews")
    op.drop_index("ix_review_created_at", table_name="reviews")
    op.drop_index("ix_review_user_thread", table_name="reviews")
    op.drop_table("reviews")
    # ### end Alembic commands ###
