"""remove notes from events

Revision ID: ec7d2cfc55f0
Revises: caf0b46811eb
Create Date: 2025-12-31 09:55:11.733867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec7d2cfc55f0'
down_revision: Union[str, Sequence[str], None] = 'caf0b46811eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_event_session_id', ['session_id'], unique=False)
        batch_op.create_index('ix_event_timestamp', ['timestamp'], unique=False)
        batch_op.drop_column('notes')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('ix_session_ended_at', ['ended_at'], unique=False)
        batch_op.create_index('ix_session_started_at', ['started_at'], unique=False)
        batch_op.create_foreign_key('fk_sessions_pending_thread_id_threads', 'threads', ['pending_thread_id'], ['id'])

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_task_id'))
        batch_op.create_index(batch_op.f('ix_tasks_task_id'), ['task_id'], unique=True)

    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.create_index('ix_thread_last_activity', ['last_activity_at'], unique=False)
        batch_op.create_index('ix_thread_position', ['queue_position'], unique=False)
        batch_op.create_index('ix_thread_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.drop_index('ix_thread_status')
        batch_op.drop_index('ix_thread_position')
        batch_op.drop_index('ix_thread_last_activity')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_task_id'))
        batch_op.create_index(batch_op.f('ix_tasks_task_id'), ['task_id'], unique=False)

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('ix_session_started_at')
        batch_op.drop_index('ix_session_ended_at')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))
        batch_op.drop_index('ix_event_timestamp')
        batch_op.drop_index('ix_event_session_id')

    # ### end Alembic commands ###
