"""FastAPI application factory and configuration."""

import logging
import os
import secrets
from pathlib import Path
from typing import cast

from fastapi import Depends, FastAPI, Request, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse, Response
from fastapi.staticfiles import StaticFiles
from starlette.staticfiles import StaticFiles as StarletteStaticFiles
from starlette.responses import Response as StarletteResponse
from starlette.types import Scope
from slowapi import _rate_limit_exceeded_handler
from slowapi.errors import RateLimitExceeded
from sqlalchemy import exc as sqlalchemy_exc
from sqlalchemy.engine import make_url
from sqlalchemy.ext.asyncio import AsyncSession
from starlette.exceptions import HTTPException as StarletteHTTPException

from app.api import (
    admin,
    analytics,
    auth,
    bug_report,
    collection,
    debug,
    dependency,
    issue,
    queue,
    rate,
    reading_orders,
    roll,
    session,
    snooze,
    test,
    thread,
    undo,
)
from app.api.review import router
from app.config import get_app_settings, get_database_settings
from app.csrf import CSRF_COOKIE_NAME, CSRF_HEADER_NAME, is_csrf_protected_request
from app.database import get_db
from app.exception_handlers import register_exception_handlers
from app.lifecycle import init_database
from app.middleware import limiter, SecurityHeadersMiddleware
from app.middleware.request_logging import add_request_logging_middleware

logger = logging.getLogger(__name__)

# Log database URL at startup (with password redacted)
_db_settings = get_database_settings()
_redacted_url = make_url(_db_settings.database_url).render_as_string(hide_password=True)
logger.info(f"Starting with DATABASE_URL: {_redacted_url}")

def create_app(*, serve_frontend: bool = True) -> FastAPI:
    """Create and configure the FastAPI application.

    Args:
        serve_frontend: Whether to mount frontend static assets and SPA routes.

    Returns:
        Configured FastAPI application instance.
    """
    app_settings = get_app_settings()

    if not logging.getLogger().hasHandlers():
        requested_level = os.getenv("LOG_LEVEL")
        env_level_map: dict[str, int] = {
            "production": logging.ERROR,
            "staging": logging.WARNING,
            "development": logging.DEBUG,
            "test": logging.WARNING,
        }
        default_level = env_level_map.get(app_settings.environment, logging.WARNING)

        if requested_level:
            level = logging.getLevelNamesMapping().get(requested_level.upper(), default_level)
        else:
            level = default_level

        logging.basicConfig(level=level)

    app = FastAPI(
        title="Dice-Driven Comic Tracker",
        description="API for tracking comic reading with dice rolls",
        version="0.1.0",
    )

    # Register rate limiter and handler for both normal and test-mode rate limiting.
    app.state.limiter = limiter

    def rate_limit_exceeded_handler(request: Request, exc: Exception) -> Response:
        """Adapt slowapi handler to FastAPI's exception handler type.

        Args:
            request: FastAPI request object.
            exc: Raised exception.

        Returns:
            Response generated by slowapi's rate limit handler.
        """
        return _rate_limit_exceeded_handler(request, cast(RateLimitExceeded, exc))

    app.add_exception_handler(RateLimitExceeded, rate_limit_exceeded_handler)

    app_settings.validate_production_cors()
    cors_origins = app_settings.cors_origins_list

    app.add_middleware(
        CORSMiddleware,
        allow_origins=cors_origins,
        allow_credentials=False,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    app.add_middleware(SecurityHeadersMiddleware)

    @app.middleware("http")
    async def csrf_middleware(request: Request, call_next):
        """Require a matching CSRF header and cookie on mutating API requests."""
        if os.getenv("TEST_ENVIRONMENT") == "true":
            return await call_next(request)
        if not is_csrf_protected_request(request.method, request.url.path):
            return await call_next(request)

        auth_header = request.headers.get("authorization")
        if not auth_header:
            return await call_next(request)

        csrf_cookie = request.cookies.get(CSRF_COOKIE_NAME)
        csrf_header = request.headers.get(CSRF_HEADER_NAME)
        if (
            not csrf_cookie
            or not csrf_header
            or not secrets.compare_digest(csrf_cookie, csrf_header)
        ):
            return JSONResponse(
                status_code=status.HTTP_403_FORBIDDEN,
                content={"detail": "CSRF token missing or invalid"},
            )

        return await call_next(request)

    # Error-only request logging (body redaction + environment-aware sanitization).
    add_request_logging_middleware(app, app_settings.environment)

    # Global, HTTP, and validation exception handlers (environment-aware logging).
    register_exception_handlers(app, app_settings)

    app.include_router(roll.router, prefix="/api/roll", tags=["roll"])
    app.include_router(router, prefix="/api/v1/reviews", tags=["reviews"])
    app.include_router(admin.router, prefix="/api", tags=["admin"])
    app.include_router(analytics.router, prefix="/api", tags=["analytics"])
    app.include_router(bug_report.router, prefix="/api/bug-reports", tags=["bug-reports"])
    app.include_router(auth.router, prefix="/api/auth", tags=["auth"])
    app.include_router(thread.router, prefix="/api/threads", tags=["threads"])
    app.include_router(collection.router, prefix="/api/v1/collections", tags=["collections"])
    if app_settings.environment != "production":
        app.include_router(debug.router, prefix="/api", tags=["debug"])
    app.include_router(issue.router, tags=["issues"])
    app.include_router(rate.router, prefix="/api/rate", tags=["rate"])
    app.include_router(queue.router, prefix="/api/queue", tags=["queue"])
    app.include_router(reading_orders.router, tags=["reading-orders"])
    app.include_router(session.router, prefix="/api/sessions", tags=["session"])
    app.include_router(session.router, prefix="/api/v1/sessions", tags=["session"])
    app.include_router(snooze.router, prefix="/api/snooze", tags=["snooze"])
    app.include_router(undo.router, prefix="/api/undo", tags=["undo"])
    app.include_router(dependency.router, prefix="/api/v1", tags=["dependencies"])
    if app_settings.environment != "production":
        app.include_router(test.router, prefix="/api", tags=["test"])

    def _assert_production_frontend_assets() -> None:
        """Ensure required frontend artifacts exist in production.

        Raises:
            RuntimeError: If required built frontend artifacts are missing.
        """
        if app_settings.environment != "production":
            return

        spa_index = Path("static/react/index.html")
        assets_dir = Path("static/react/assets")
        has_js = any(assets_dir.glob("*.js")) if assets_dir.exists() else False
        has_css = any(assets_dir.glob("*.css")) if assets_dir.exists() else False

        if not spa_index.exists() or not assets_dir.exists() or not has_js or not has_css:
            raise RuntimeError(
                "Missing built frontend artifacts in production. "
                "Expected static/react/index.html and static/react/assets with JS/CSS files."
            )

    @app.api_route(
        "/api/{path:path}",
        methods=["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS", "HEAD"],
    )
    async def api_not_found(path: str) -> JSONResponse:
        """Return a JSON 404 for unknown API routes.

        Args:
            path: API path that was not found.

        Returns:
            JSON response with 404 status code.
        """
        return JSONResponse(status_code=status.HTTP_404_NOT_FOUND, content={"detail": "Not Found"})

    class CacheControlledStaticFiles(StarletteStaticFiles):
        """StaticFiles with explicit cache-control headers for hashed assets."""

        async def get_response(self, path: str, scope: Scope) -> StarletteResponse:
            """Get static file response with cache-control headers.

            Args:
                path: The path to the static file.
                scope: ASGI scope containing request information.

            Returns:
                A Starlette response with cache-control headers for hashed assets.
            """
            response = await super().get_response(path, scope)
            # Add cache headers for hashed assets (they have content hashes in filename)
            if hasattr(response, "headers"):
                # Cache hashed assets (contain hash like index-DsWHcseo.js) for 1 year
                # These never change content for the same URL
                response.headers["Cache-Control"] = "public, max-age=31536000, immutable"
            return response

    if serve_frontend:
        # Mount static files. In production, enforce artifact presence before mounting.
        if app_settings.environment == "production":
            _assert_production_frontend_assets()
            app.mount("/static", StaticFiles(directory="static"), name="static")
            app.mount(
                "/assets",
                CacheControlledStaticFiles(directory="static/react/assets"),
                name="assets",
            )
        else:
            if Path("static").exists():
                app.mount("/static", StaticFiles(directory="static"), name="static")
            if Path("static/react/assets").exists():
                app.mount("/assets", StaticFiles(directory="static/react/assets"), name="assets")

        @app.get("/vite.svg")
        async def serve_vite_svg():
            """Serve vite favicon.

            Returns:
                FileResponse with vite.svg file.
            """
            from fastapi.responses import FileResponse

            return FileResponse("static/vite.svg", media_type="image/svg+xml")

        def _serve_spa_index_response() -> Response:
            """Serve SPA index file when available, else return fallback HTML.

            Returns:
                FileResponse for the built SPA index, or fallback HTMLResponse in test environments.
            """
            from fastapi.responses import FileResponse, HTMLResponse

            spa_index = Path("static/react/index.html")
            cache_headers = {"Cache-Control": "no-store, no-cache, must-revalidate"}
            if spa_index.exists():
                return FileResponse(str(spa_index), headers=cache_headers)
            if app_settings.environment == "production":
                raise StarletteHTTPException(status_code=503, detail="Frontend assets unavailable")
            fallback_html = "<!doctype html><html><body><div id='root'></div></body></html>"
            return HTMLResponse(fallback_html, headers=cache_headers)

        @app.get("/")
        async def serve_root():
            """Serve React app at root URL.

            Returns:
                FileResponse with React index.html.
            """
            return _serve_spa_index_response()

        @app.get("/react")
        async def serve_react_redirect():
            """Redirect /react to / for consistent routing.

            Returns:
                RedirectResponse to root URL.
            """
            from fastapi.responses import RedirectResponse

            return RedirectResponse("/", status_code=301)

        @app.get("/react/")
        async def serve_react_redirect_slash():
            """Redirect /react/ to / for consistent routing.

            Returns:
                RedirectResponse to root URL.
            """
            from fastapi.responses import RedirectResponse

            return RedirectResponse("/", status_code=301)

    @app.get("/health", response_model=None)
    async def health_check(db: AsyncSession = Depends(get_db)) -> dict | JSONResponse:
        """Health check endpoint that verifies basic application functionality.

        Returns:
            JSON response with health status and database connection state.
        """
        from sqlalchemy import text

        try:
            await db.execute(text("SELECT 1"))
            return {"status": "healthy", "database": "connected"}
        except sqlalchemy_exc.DBAPIError as e:
            logger.error(f"Health check database connection failed: {e}")
            return JSONResponse(
                status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                content={"status": "unhealthy", "database": "disconnected", "error": str(e)},
            )

    if serve_frontend:

        @app.get("/{full_path:path}")
        async def serve_react_spa(full_path: str):
            """Serve the React SPA for non-API routes.

            The React app owns routing for paths like /rate, /queue, /history, etc.

            Args:
                full_path: The path to serve.

            Returns:
                FileResponse with React index.html.

            Raises:
                StarletteHTTPException: If path is blocked.
            """
            blocked_prefixes = ("api", "static", "assets", "debug")
            blocked_exact = {"health", "openapi.json", "docs", "redoc", "vite.svg"}

            if (
                full_path in blocked_exact
                or full_path in blocked_prefixes
                or any(full_path.startswith(prefix + "/") for prefix in blocked_prefixes)
            ):
                raise StarletteHTTPException(status_code=404, detail="Not Found")

            return _serve_spa_index_response()

    @app.on_event("startup")
    async def startup_event():
        """Initialize database on application startup."""
        await init_database(app_settings.environment)

    return app


app = create_app()
